/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectperpustakaan;
import crudBuku.DeleteDbBuku;
import crudBuku.UpdateDbBuku;
import crudBuku.CreateDbBuku;
import crudBuku.CreateDbBuku;
import crudBuku.DeleteDbBuku;
import crudBuku.TampilDataBuku;
import crudBuku.UpdateDbBuku;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class DataBuku extends javax.swing.JFrame {

    /**
     * Creates new form DataBuku
     */
    TampilDataBuku tampilData = new TampilDataBuku();
    int selectedRow = -1;
    
    public DataBuku() {
        initComponents();
        String[] columns = {
          "Kode Buku", 
          "Judul Buku", 
          "Nama Pengarang", 
          "Penerbit", 
          "Tahun Terbit", 
          "Jenis Buku", 
          "Buku Tersedia"
        };
        
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        this.tabelDataBuku.setModel(model);
        ResultSet rs = tampilData.tampilkanDataSemuaBuku();
        
        try{
            int i = 0;
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("kode_buku"), rs.getString("judul_buku"),rs.getString("nama_pengarang"), rs.getString("penerbit"), rs.getString("tahun_terbit"), rs.getString("jenis_buku"), rs.getString("jumlah_buku_tersedia")});
                i++;
            }
        }catch(SQLException e){
            System.out.println("Pesan Error : " + e.getMessage());
        }
        
        this.tabelDataBuku.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void mousePressed(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                int row = tabelDataBuku.getSelectedRow();
                selectedRow = row;
                inpKodeBuku.setText(tabelDataBuku.getValueAt(row, 0).toString());
                inpJudulBuku.setText(tabelDataBuku.getValueAt(row, 1).toString());
                inpNamaPengarang.setText(tabelDataBuku.getValueAt(row, 2).toString());
                inpPenerbit.setText(tabelDataBuku.getValueAt(row, 3).toString());
                inpTahunTerbit.setText(tabelDataBuku.getValueAt(row, 4).toString());
                inpJenisBuku.setText(tabelDataBuku.getValueAt(row, 5).toString());
                inpJumlahBuku.setText(tabelDataBuku.getValueAt(row, 7).toString());
            }

            @Override
            public void mouseReleased(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void mouseEntered(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void mouseExited(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        } );
        
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inpPenerbit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inpTahunTerbit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inpJenisBuku = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inpJumlahBuku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataBuku = new javax.swing.JTable();
        btnSimpanBuku = new javax.swing.JButton();
        buttonEditBuku = new javax.swing.JButton();
        buttonHapusBuku = new javax.swing.JButton();
        buttonCariBuku = new javax.swing.JButton();
        inpCariBuku = new javax.swing.JTextField();
        buttonKeluarBuku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inpKodeBuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inpJudulBuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inpNamaPengarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(124, 133, 148));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 46, 53), 12, true));

        inpPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpPenerbitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel6.setText("Tahun Terbit : ");

        inpTahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTahunTerbitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel7.setText("Jenis Buku :");

        inpJenisBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpJenisBukuActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel9.setText("Jumlah Buku :");

        inpJumlahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpJumlahBukuActionPerformed(evt);
            }
        });

        tabelDataBuku.setFont(new java.awt.Font("Schadow BT", 0, 12)); // NOI18N
        tabelDataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul Buku", "Nama Pengarang", "Penerbit", "Tahun Terbit", "Jenis Buku", "Jumlah Buku"
            }
        ));
        tabelDataBuku.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelDataBukuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelDataBuku);

        btnSimpanBuku.setBackground(new java.awt.Color(74, 88, 89));
        btnSimpanBuku.setFont(new java.awt.Font("Schadow BT", 0, 12)); // NOI18N
        btnSimpanBuku.setForeground(new java.awt.Color(237, 237, 237));
        btnSimpanBuku.setText("Simpan");
        btnSimpanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanBukuActionPerformed(evt);
            }
        });

        buttonEditBuku.setBackground(new java.awt.Color(74, 88, 89));
        buttonEditBuku.setFont(new java.awt.Font("Schadow BT", 0, 12)); // NOI18N
        buttonEditBuku.setForeground(new java.awt.Color(239, 239, 239));
        buttonEditBuku.setText("Edit");
        buttonEditBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditBukuActionPerformed(evt);
            }
        });

        buttonHapusBuku.setBackground(new java.awt.Color(74, 88, 89));
        buttonHapusBuku.setFont(new java.awt.Font("Schadow BT", 0, 12)); // NOI18N
        buttonHapusBuku.setForeground(new java.awt.Color(238, 238, 238));
        buttonHapusBuku.setText("Hapus");
        buttonHapusBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusBukuActionPerformed(evt);
            }
        });

        buttonCariBuku.setBackground(new java.awt.Color(105, 129, 141));
        buttonCariBuku.setFont(new java.awt.Font("Schadow BT", 0, 12)); // NOI18N
        buttonCariBuku.setForeground(new java.awt.Color(238, 238, 238));
        buttonCariBuku.setText("Cari");
        buttonCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariBukuActionPerformed(evt);
            }
        });

        inpCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCariBukuActionPerformed(evt);
            }
        });

        buttonKeluarBuku.setBackground(new java.awt.Color(93, 107, 107));
        buttonKeluarBuku.setFont(new java.awt.Font("Schadow BT", 0, 12)); // NOI18N
        buttonKeluarBuku.setForeground(new java.awt.Color(239, 239, 239));
        buttonKeluarBuku.setText("Keluar");
        buttonKeluarBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarBukuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        jLabel1.setText("DATA BUKU");

        jLabel2.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel2.setText("Kode Buku : ");

        inpKodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpKodeBukuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel3.setText("Judul Buku : ");

        inpJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpJudulBukuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel4.setText("Nama Pengarang :");

        inpNamaPengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNamaPengarangActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel5.setText("Penerbit :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inpJumlahBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(inpTahunTerbit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inpJenisBuku, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inpPenerbit)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inpNamaPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inpKodeBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(inpJudulBuku))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inpCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnSimpanBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(buttonHapusBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKeluarBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(105, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(inpCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCariBuku))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpNamaPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpTahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpJenisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKeluarBuku)
                    .addComponent(buttonHapusBuku)
                    .addComponent(buttonEditBuku)
                    .addComponent(btnSimpanBuku)
                    .addComponent(inpJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpKodeBukuActionPerformed

    private void inpJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpJudulBukuActionPerformed

    private void inpNamaPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNamaPengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNamaPengarangActionPerformed

    private void inpPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpPenerbitActionPerformed

    private void inpTahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpTahunTerbitActionPerformed

    private void inpJenisBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpJenisBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpJenisBukuActionPerformed

    private void inpJumlahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpJumlahBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpJumlahBukuActionPerformed

    private void inpCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCariBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCariBukuActionPerformed

    private void buttonKeluarBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarBukuActionPerformed
        dispose();
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_buttonKeluarBukuActionPerformed

    private void btnSimpanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBukuActionPerformed
        CreateDbBuku inputData = new CreateDbBuku();
        DefaultTableModel tabelData2 = (DefaultTableModel) tabelDataBuku.getModel();   
   
        inputData.inputData(Integer.parseInt(inpKodeBuku.getText()),inpJudulBuku.getText(),inpNamaPengarang.getText(),inpPenerbit.getText(),Integer.parseInt(inpTahunTerbit.getText()),inpJenisBuku.getText(),Integer.parseInt(inpJumlahBuku.getText()));
        ResultSet rs = tampilData.tampilkanData(this.inpKodeBuku.getText());
        try{
            
            if(rs.next()){
                tabelData2.addRow(new Object[]{rs.getString("kode_buku"), rs.getString("judul_buku"),rs.getString("nama_pengarang"), rs.getString("penerbit"), rs.getString("tahun_terbit"), rs.getString("jenis_buku"), rs.getString("jumlah_buku_tersedia")});
            } else{
                System.out.println("Data tidak bisa ditampilkan");
            }
        }catch(SQLException e){
            System.out.println("Pesan Error : " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanBukuActionPerformed

    private void tabelDataBukuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelDataBukuAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelDataBukuAncestorAdded

    private void buttonEditBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditBukuActionPerformed
        // TODO add your handling code here:
        UpdateDbBuku updateData = new UpdateDbBuku();
        updateData.updateData(Integer.parseInt(inpKodeBuku.getText()),inpJudulBuku.getText(),inpNamaPengarang.getText(),inpPenerbit.getText(),Integer.parseInt(inpTahunTerbit.getText()),inpJenisBuku.getText(),Integer.parseInt(inpJumlahBuku.getText()));
        DefaultTableModel tabel = (DefaultTableModel) tabelDataBuku.getModel();
        tabel.addRow(new Object[]{inpKodeBuku.getText(), inpJudulBuku.getText(), inpNamaPengarang.getText(),inpPenerbit.getText(), inpTahunTerbit.getText(), inpJenisBuku.getText(), inpJumlahBuku.getText()});
        tabel.removeRow(selectedRow);
    }//GEN-LAST:event_buttonEditBukuActionPerformed

    private void buttonHapusBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusBukuActionPerformed
        //TODO add your handling code here:
        DeleteDbBuku deleteData = new DeleteDbBuku();
        deleteData.deleteData(inpKodeBuku.getText());
        DefaultTableModel tabel = (DefaultTableModel) tabelDataBuku.getModel();
        tabel.removeRow(selectedRow);
        inpKodeBuku.setText("");
        inpJudulBuku.setText("");
        inpNamaPengarang.setText("");
        inpTahunTerbit.setText("");
        inpJenisBuku.setText("");
        inpJumlahBuku.setText("");
    }//GEN-LAST:event_buttonHapusBukuActionPerformed

    private void buttonCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariBukuActionPerformed
                ResultSet rs;
        if(!"".equals(inpCariBuku.getText())) {
            rs = tampilData.tampilkanData(inpCariBuku.getText());
        } else {
            rs = tampilData.tampilkanDataSemuaBuku();
        }
        
        DefaultTableModel tabel = (DefaultTableModel) tabelDataBuku.getModel();
        
        try{
            for(var i = tabel.getRowCount() - 1; i >= 0; i--) {
                tabel.removeRow(i);
            }
            while(rs.next()){
                tabel.addRow(new Object[]{rs.getInt("kode_buku"), rs.getString("judul_buku"),rs.getString("nama_pengarang"), rs.getString("penerbit"), rs.getString("tahun_terbit"), rs.getString("jenis_buku"), rs.getString("status"), rs.getString("jumlah_buku_tersedia")});
            }
            
        }catch(SQLException e){
            System.out.println("Pesan Error : " + e.getMessage());
        }
    }//GEN-LAST:event_buttonCariBukuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanBuku;
    private javax.swing.JButton buttonCariBuku;
    private javax.swing.JButton buttonEditBuku;
    private javax.swing.JButton buttonHapusBuku;
    private javax.swing.JButton buttonKeluarBuku;
    private javax.swing.JTextField inpCariBuku;
    private javax.swing.JTextField inpJenisBuku;
    private javax.swing.JTextField inpJudulBuku;
    private javax.swing.JTextField inpJumlahBuku;
    private javax.swing.JTextField inpKodeBuku;
    private javax.swing.JTextField inpNamaPengarang;
    private javax.swing.JTextField inpPenerbit;
    private javax.swing.JTextField inpTahunTerbit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataBuku;
    // End of variables declaration//GEN-END:variables
}
