/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectperpustakaan;

import crudBuku.UpdateDbBuku;
import crudTransaksi.DeleteDbTransaksi;
import crudTransaksi.UpdateDbTransaksi;
import java.util.Date;

/**
 *
 * @author ACER
 */
public class PengembalianBuku extends javax.swing.JFrame {


    /**
     * Creates new form PengembalianBuku
     * @param kodeBuku
     * @param nim
     * @param nama
     * @param peminjamanBuku
     * @param pengembalianBuku
     * @param pengembalianBukuAnggota
     * @param idTransaksi
     * @param denda
     */
    int kodeBuku;
    Date pengembalianBuku;
    Date pengembalianBukuAnggota;
    int idTransaksi;
    double denda;
    public PengembalianBuku(int kodeBuku, String nim, String nama, Date peminjamanBuku, Date pengembalianBuku, Date pengembalianBukuAnggota, int idTransaksi, double denda) {
        initComponents();
        this.kodeBuku = kodeBuku;
        this.pengembalianBuku = pengembalianBuku;
        this.pengembalianBukuAnggota = pengembalianBukuAnggota;
        this.idTransaksi = idTransaksi;
        this.denda = denda;
        this.labelKodeBuku.setText(String.format("%s", kodeBuku));
        this.labelNim.setText(String.format("%s", nim));
        this.labelNama.setText(String.format("%s", nama));
        this.labelTanggalPeminjaman.setText(String.format("%s", peminjamanBuku));
        this.labelTenggat.setText(String.format("%s", pengembalianBuku));
        this.labelTanggalPengembalian.setText(String.format("%s", pengembalianBukuAnggota));
        this.labelIdTransaksi.setText(String.format("%s", idTransaksi));
        this.labelDenda.setText(String.format("%s", denda));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelNim = new javax.swing.JLabel();
        labelTanggalPeminjaman = new javax.swing.JLabel();
        labelTenggat = new javax.swing.JLabel();
        labelIdTransaksi = new javax.swing.JLabel();
        labelDenda = new javax.swing.JLabel();
        labelTanggalPengembalian = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelKodeBuku = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnKembalikan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(710, 578));

        jPanel2.setBackground(new java.awt.Color(124, 133, 148));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 46, 53), 10, true));

        jLabel10.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel10.setText("Denda ");

        labelNim.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        labelNim.setText("jLabel1");

        labelTanggalPeminjaman.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        labelTanggalPeminjaman.setText("jLabel1");

        labelTenggat.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        labelTenggat.setText("jLabel1");

        labelIdTransaksi.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        labelIdTransaksi.setText("jLabel1");

        labelDenda.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        labelDenda.setText("jLabel1");

        labelTanggalPengembalian.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        labelTanggalPengembalian.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel1.setText("Kode Buku ");

        labelKodeBuku.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        labelKodeBuku.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel3.setText("Nama ");

        labelNama.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        labelNama.setText("jLabel1");

        jLabel5.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel5.setText("NIM ");

        jLabel6.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Peminjaman Buku ");

        jLabel7.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Tenggat Pengembalian Buku ");

        jLabel8.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal Pengembalian Buku :");

        jLabel9.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel9.setText("ID Transaksi  ");

        jLabel17.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        jLabel17.setText("DETAIL TRANSAKSI");

        btnKembalikan.setBackground(new java.awt.Color(93, 107, 107));
        btnKembalikan.setFont(new java.awt.Font("Schadow BT", 0, 12)); // NOI18N
        btnKembalikan.setForeground(new java.awt.Color(234, 234, 234));
        btnKembalikan.setText("Kembalian");
        btnKembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalikanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(163, 163, 163)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(64, 64, 64))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTanggalPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTenggat, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(labelTanggalPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(btnKembalikan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 168, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelKodeBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelNama))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNim))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelTanggalPeminjaman))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelTenggat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelTanggalPengembalian))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelIdTransaksi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelDenda))
                .addGap(49, 49, 49)
                .addComponent(btnKembalikan)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalikanActionPerformed
        UpdateDbTransaksi updateDbTransaksi = new UpdateDbTransaksi();
        updateDbTransaksi.updateData(pengembalianBuku.toString(), pengembalianBukuAnggota.toString(), idTransaksi, denda);
        DeleteDbTransaksi deleteDbTransaksi = new DeleteDbTransaksi();
        deleteDbTransaksi.deleteData(String.format("%s", idTransaksi), rootPane);
        UpdateDbBuku updateDbBuku = new UpdateDbBuku();
        updateDbBuku.kembalikanBuku(kodeBuku);
        dispose();
        Transaksi transaksi = new Transaksi();
        transaksi.setVisible(true);
    }//GEN-LAST:event_btnKembalikanActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembalikan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDenda;
    private javax.swing.JLabel labelIdTransaksi;
    private javax.swing.JLabel labelKodeBuku;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNim;
    private javax.swing.JLabel labelTanggalPeminjaman;
    private javax.swing.JLabel labelTanggalPengembalian;
    private javax.swing.JLabel labelTenggat;
    // End of variables declaration//GEN-END:variables
}
